### ISSUE TITLE
About RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by alice-cool** [deeplab-ai/atr-net#6]
Dear scholar,
  I want to ask about the size of cuda memory by running the code

> python3 main.py --dataset=VG200 --task=sggen --model=atr_net

 I want to evaluate the model. And my cuda is 24G  but running the below code will throw the error "RuntimeError: CUDA error: out of memory"

/home/byd/atr-net/faster_rcnn/model/utils/config.py:375: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = edict(yaml.load(f))
load checkpoint faster_rcnn/faster_rcnn_1_10_14657.pth
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from src.models import (
  File "/home/byd/atr-net/src/models/atr_net.py", line 21, in <module>
    from src.utils.train_test_utils import SGGTrainTester
  File "/home/byd/atr-net/src/utils/train_test_utils.py", line 13, in <module>
    from src.utils.data_loading_utils import (
  File "/home/byd/atr-net/src/utils/data_loading_utils.py", line 14, in <module>
    FEATURE_EXTRACTOR = BaseFeatureExtractor()
  File "/home/byd/atr-net/src/tools/feature_extractors.py", line 80, in __init__
    checkpoint = _load()
  File "/home/byd/atr-net/src/tools/feature_extractors.py", line 67, in _load
    checkpoint = torch.load(load_name)
  File "/home/byd/.conda/envs/vilbert-mt/lib/python3.6/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/byd/.conda/envs/vilbert-mt/lib/python3.6/site-packages/torch/serialization.py", line 772, in _legacy_load
    result = unpickler.load()
  File "/home/byd/.conda/envs/vilbert-mt/lib/python3.6/site-packages/torch/serialization.py", line 728, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/byd/.conda/envs/vilbert-mt/lib/python3.6/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/byd/.conda/envs/vilbert-mt/lib/python3.6/site-packages/torch/serialization.py", line 155, in _cuda_deserialize
    return storage_type(obj.size())
  File "/home/byd/.conda/envs/vilbert-mt/lib/python3.6/site-packages/torch/cuda/__init__.py", line 484, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: out of memory

**Comment by nickgkan** [comment]
Hi,

From the trace, it seems that you're facing the OOM error early, during the import phase. Is it possible that you're running multiple experiments on the same gpu?

This code can run on 12G or less.

**Comment by alice-cool** [comment]
Thanks for your useful suggestion. Thanks again. Your project is so elegant.

**Comment by alice-cool** [comment]
> Hi,
> 
> From the trace, it seems that you're facing the OOM error early, during the import phase. Is it possible that you're running multiple experiments on the same gpu?
> 
> This code can run on 12G or less.

Dear scholar,
 I want to ask about your pretrained weights file download link for object_detector, atr_net.
Do you upload these file, or we only train the corresponding code to produce the file, to evaluate on new raw images?

**Comment by nickgkan** [comment]
I'm sorry, we don't offer pretrained weights, it should be easy to replicate the results though with the default config files.

**Comment by alice-cool** [comment]
Thanks for you all the time.&nbsp;



---原始邮件---
发件人: "Nikolaos ***@***.***&gt;
发送时间: 2021年8月30日(星期一) 凌晨0:37
收件人: ***@***.***&gt;;
抄送: "State ***@***.******@***.***&gt;;
主题: Re: [deeplab-ai/atr-net] About RuntimeError: CUDA error: out of memory (#6)




 
I'm sorry, we don't offer pretrained weights, it should be easy to replicate the results though with the default config files.
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
